syntax enable
set background=dark
set backspace=indent,eol,start
set laststatus=2
set number
set hlsearch
set nowrap
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set paste
set mouse=a

set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\:h9
let g:Powerline_symbols='fancy'
set encoding=utf-8

set fillchars+=stl:\ ,stlnc:\
set term=xterm-256color
set termencoding=utf-8

set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/

" Always show statusline
set laststatus=2

set cul cuc

hi CursorColumn cterm=NONE ctermbg=236 ctermfg=NONE gui=NONE guibg=#2d2d2d guifg=NONE
hi CursorLine   cterm=NONE ctermbg=236 ctermfg=NONE gui=NONE guibg=#2d2d2d guifg=NONE

"if &bg == 'dark'
"    hi CursorLine gui=NONE guibg=#333333
"else
"    hi CursorLine gui=NONE guibg=#CCCCCC
"endif
"
